# Generated by Django 4.1.6 on 2023-02-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movementbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_channel',
            field=models.TextField(default=1, verbose_name='Id канала'),
            preserve_default=False,
        ),
    ]
