# Generated by Django 4.1.6 on 2023-02-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movementbot', '0002_profile_id_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foreign_id',
            field=models.IntegerField(default=1, verbose_name='Id пользователя'),
            preserve_default=False,
        ),
    ]
